version: '3'

services:
          web:
               build: .
               command: bash -c "cd vitaemanager && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
               container_name: unica
               volumes:
                       - .:/unica:Z
               ports:
                        - "8000:8000"
