# Generated by Django 3.0.2 on 2020-01-28 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppServicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('duracao', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='AppAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=5)),
                ('servico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppServicos')),
            ],
        ),
    ]
