# Generated by Django 3.0.2 on 2020-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTextos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('pagina', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appservicos',
            name='descricao',
            field=models.TextField(),
        ),
    ]
