# Generated by Django 3.0.2 on 2020-01-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200129_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptextos',
            options={'verbose_name': 'Texto do Site', 'verbose_name_plural': 'Textos do Site'},
        ),
    ]
