# Generated by Django 3.0.2 on 2020-01-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200129_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appservicos',
            options={'verbose_name': 'Serviços', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='appservicos',
            name='duracao',
            field=models.CharField(max_length=4),
        ),
    ]
